services:
  db:
    image: mysql:8.0
    container_name: food-db
    restart: always
    environment:
      MYSQL_DATABASE: food_delivery
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - food-net

  backend:
    build:
      context: .                   # root folder
      dockerfile: Dockerfile.backend
    container_name: food-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/food_delivery
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - food-net

  frontend:
    build:
      context: .                   # root folder
      dockerfile: Dockerfile.frontend
    container_name: food-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - food-net

volumes:
  db_data:

networks:
  food-net:
